name: 'Code Push to Main'
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code push to main
        run: |
          echo "Code push to main"