name: "Validate Only HTML Files in Web Folder"

on:
  push:
    branches:
      - main # Replace 'main' with the branch you want to monitor

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for Web Folder
        run: |
          if [ ! -d "web" ]; then
            echo "Error: 'web' folder not found in the main branch."
            exit 1